# config.yaml
server:
  port: 80
redis:
  host: localhost
  port: 6379
db:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: 123
  databasename: ljhdb
  max-idle-conns: 20
  max-open-conns: 100
  migration-dir: db/mariadb/migrations
jwt:
  access-token-duration: 0.5m #minutes
  refresh-token-duration: 168h  #7*24 #hours
  jwt-access-secret: Sj.$#&*@(+-~`3950Mgt
  jwt-refresh-secret: Wy&^3%&*6Zst`+-H)6